# This file was generated by GoReleaser. DO NOT EDIT.
cask "camp-graph" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-macOS-x86_64.tar.gz"
      sha256 "52c9f44c81a6e7b5e5dfc4cf7dc2853741fd4e61132a6defccc30ca02deff0da"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-macOS-arm64.tar.gz"
      sha256 "44831555add80469fd529d38d4e3be6e68da6b92aa1b9ae971df222737c53810"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-linux-x86_64.tar.gz"
      sha256 "7ccbd84aa9752fad65e2b0129bc07c985b515812a88c6b4018f2079ba9712a53"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-linux-arm64.tar.gz"
      sha256 "8e543ed8c9b4e88094ae85af59901fd8a42c5c650b62e9f16d8424c4179818a5"
    end
  end

  name "camp-graph"
  desc "Knowledge graph visualization plugin for the camp CLI"
  homepage "https://github.com/Obedience-Corp/camp-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "camp-graph"
  bash_completion "completions/camp-graph.bash"
  fish_completion "completions/camp-graph.fish"
  zsh_completion "completions/_camp-graph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/camp-graph"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    camp discovers this plugin automatically once the binary is on your PATH:

      camp graph build

    Standalone completion activation:

      source <(camp-graph completion bash)
      source <(camp-graph completion zsh)
      camp-graph completion fish | source
  EOS
end
