# This file was generated by GoReleaser. DO NOT EDIT.
cask "camp-graph" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-macOS-x86_64.tar.gz"
      sha256 "d5d1eb42a1bac616472ae713585b1b1c88ec61275b642871cceea797801140f4"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-macOS-arm64.tar.gz"
      sha256 "eadc16fe1d69c31adcf0ff638af728b3db28a1e7691faaa56a958c160fe03e73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-linux-x86_64.tar.gz"
      sha256 "2862c1db8dfc3011be481d54165ae05aa9087a520ba3f9954828e213965048c2"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-linux-arm64.tar.gz"
      sha256 "dce1fbcd0a11d7d1c7b63e1aca3c7bbd5085a2698970bf94df02a62aa0d3c188"
    end
  end

  name "camp-graph"
  desc "Knowledge graph visualization plugin for the camp CLI"
  homepage "https://github.com/Obedience-Corp/camp-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "camp-graph"
  bash_completion "completions/camp-graph.bash"
  fish_completion "completions/camp-graph.fish"
  zsh_completion "completions/_camp-graph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/camp-graph"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    camp discovers this plugin automatically once the binary is on your PATH:

      camp graph build

    Standalone completion activation:

      source <(camp-graph completion bash)
      source <(camp-graph completion zsh)
      camp-graph completion fish | source
  EOS
end
