# This file was generated by GoReleaser. DO NOT EDIT.
cask "camp-graph" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-macOS-x86_64.tar.gz"
      sha256 "f341f6b27d44d3c27dccdb84a7ae25d48f94f5afc921595d83a8cb2d20ec470b"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-macOS-arm64.tar.gz"
      sha256 "9e7beb8ee9ca9f599ee1bbb250be14d6a6bf2a1866d4993e923f6d94881d59dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-linux-x86_64.tar.gz"
      sha256 "aea24bf6601fc3d414831f2dae0965c31dd94aff643588852113671184aea77c"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/camp-graph/releases/download/v#{version}/camp-graph-#{version}-linux-arm64.tar.gz"
      sha256 "78d7737f61f6b05640ccc9dab9ab6442d807f7d5368f97bf0052e90ad638d12f"
    end
  end

  name "camp-graph"
  desc "Knowledge graph visualization plugin for the camp CLI"
  homepage "https://github.com/Obedience-Corp/camp-graph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "camp-graph"
  bash_completion "completions/camp-graph.bash"
  fish_completion "completions/camp-graph.fish"
  zsh_completion "completions/_camp-graph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/camp-graph"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    camp discovers this plugin automatically once the binary is on your PATH:

      camp graph build

    Standalone completion activation:

      source <(camp-graph completion bash)
      source <(camp-graph completion zsh)
      camp-graph completion fish | source
  EOS
end
