# This file was generated by GoReleaser. DO NOT EDIT.
cask "festival" do
  version "0.2.2"

  on_macos do
    url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-macOS-all.tar.gz"
    sha256 "42c9e893ba6d83369af7c9ea3c63b3d163be74e46a524f03876440e2c1e6e588"
  end

  on_linux do
    on_intel do
      url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-linux-x86_64.tar.gz"
      sha256 "535ec7a20092fb7745614a35be1261e90dbf9dd2740dd8ff9e4d6b7689bd2038"
    end
    on_arm do
      url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-linux-arm64.tar.gz"
      sha256 "4bb484631fb728564cbed76b413b9c20aad6378db4f43a96bd07a5e8d7081566"
    end
  end

  name "festival"
  desc "Festival Methodology CLI suite (fest + camp)"
  homepage "https://github.com/Obedience-Corp/festival"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fest"
  binary "camp"
  bash_completion "completions/fest.bash"
  fish_completion "completions/fest.fish"
  zsh_completion "completions/_fest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fest", "#{staged_path}/camp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To activate shell completions and camp shell integration, add to your shell config:

      # bash (~/.bashrc)
      eval \"$(camp shell-init bash)\"
      source <(fest completion bash)

      # zsh (~/.zshrc)
      eval \"$(camp shell-init zsh)\"
      source <(fest completion zsh)

      # fish (~/.config/fish/config.fish)
      camp shell-init fish | source
      fest completion fish | source
  EOS
end
