# This file was generated by GoReleaser. DO NOT EDIT.
cask "festival" do
  version "0.3.19"

  on_macos do
    sha256 "77302cb52f27f2e46502338ce768180d5406fc40f11d5add759e6f956ef9e3b1"
    url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-macOS-all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "08137a006ae98ecaf445a3a5967937896db8d609927ce9f464d58115e34bebb6"
      url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "2823e8d417b95209901505d73c09f1b62d14df6282a45f1b4c6eb516a6e5928a"
      url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-linux-x86_64.tar.gz"
    end
  end

  name "festival"
  desc "Festival Methodology CLI suite (fest, camp, and festival)"
  homepage "https://github.com/Obedience-Corp/festival"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fest"
  binary "camp"
  binary "festival"
  bash_completion "completions/fest.bash"
  fish_completion "completions/fest.fish"
  zsh_completion "completions/_fest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fest", "#{staged_path}/camp", "#{staged_path}/festival"]
    end
    shell_dir = "#{HOMEBREW_PREFIX}/share/festival/shell"
    system_command "/bin/mkdir", args: ["-p", shell_dir, "#{HOMEBREW_PREFIX}/etc/bash_completion.d", "#{HOMEBREW_PREFIX}/share/zsh/site-functions", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/cp", args: ["#{staged_path}/shell/festival.bash", "#{shell_dir}/festival.bash"]
    system_command "/bin/cp", args: ["#{staged_path}/shell/festival.zsh", "#{shell_dir}/festival.zsh"]
    system_command "/bin/cp", args: ["#{staged_path}/shell/festival.fish", "#{shell_dir}/festival.fish"]
    # BEGIN GENERATED HOMEBREW EXTRA COMPLETION INSTALL
    system_command "/bin/cp", args: ["#{staged_path}/completions/camp.bash", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/camp"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/_camp", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_camp"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/camp.fish", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/camp.fish"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/festival.bash", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/festival"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/_festival", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_festival"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/festival.fish", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/festival.fish"]
    # END GENERATED HOMEBREW EXTRA COMPLETION INSTALL
  end

  uninstall_postflight do
    system_command "/bin/rm", args: [
      "-f",
      "#{HOMEBREW_PREFIX}/share/festival/shell/festival.bash",
      "#{HOMEBREW_PREFIX}/share/festival/shell/festival.zsh",
      "#{HOMEBREW_PREFIX}/share/festival/shell/festival.fish",
      # BEGIN GENERATED HOMEBREW EXTRA COMPLETION UNINSTALL
      "#{HOMEBREW_PREFIX}/etc/bash_completion.d/camp",
      "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_camp",
      "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/camp.fish",
      "#{HOMEBREW_PREFIX}/etc/bash_completion.d/festival",
      "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_festival",
      "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/festival.fish",
      # END GENERATED HOMEBREW EXTRA COMPLETION UNINSTALL
    ]
  end

  # No zap stanza required

  caveats <<~EOS
    Run festival setup to create your first camp. Existing camps are preserved.

    Homebrew installs static fest, camp, and festival completions. This cask does not
    edit your shell rc. To activate navigation helpers (cgo, cr, csw, cint, fgo, fls),
    add one line to your shell config:

      # bash (~/.bashrc)
      source \"$(brew --prefix)/share/festival/shell/festival.bash\"

      # zsh (~/.zshrc)
      source \"$(brew --prefix)/share/festival/shell/festival.zsh\"

      # fish (~/.config/fish/config.fish)
      source \"$(brew --prefix)/share/festival/shell/festival.fish\"

    Do not run festival install (that plants a second copy under ~/.obey/installer).
    Upgrade with: brew upgrade --cask festival
  EOS
end
