# This file was generated by GoReleaser. DO NOT EDIT.
cask "festival" do
  version "0.2.13"

  on_macos do
    sha256 "3c7761574da831d1afd91f5610dd7f07995ebbaf06131836d3b942a7f99a1fdd"
    url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-macOS-all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "a1b481fb37636b31669b46ce8abc8ffd4c12889cf255ed51d5e1d9299b93190d"
      url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "cf9381e630afff89206b2c956ae3d95a65db419c92f490f0beb4aa8d95a6c371"
      url "https://github.com/Obedience-Corp/festival/releases/download/v#{version}/festival-#{version}-linux-arm64.tar.gz"
    end
  end

  name "festival"
  desc "Festival Methodology CLI suite (fest + camp)"
  homepage "https://github.com/Obedience-Corp/festival"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fest"
  binary "camp"
  bash_completion "completions/fest.bash"
  fish_completion "completions/fest.fish"
  zsh_completion "completions/_fest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fest", "#{staged_path}/camp"]
    end
    shell_dir = "#{HOMEBREW_PREFIX}/share/festival/shell"
    system_command "/bin/mkdir", args: ["-p", shell_dir, "#{HOMEBREW_PREFIX}/etc/bash_completion.d", "#{HOMEBREW_PREFIX}/share/zsh/site-functions", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/cp", args: ["#{staged_path}/shell/festival.bash", "#{shell_dir}/festival.bash"]
    system_command "/bin/cp", args: ["#{staged_path}/shell/festival.zsh", "#{shell_dir}/festival.zsh"]
    system_command "/bin/cp", args: ["#{staged_path}/shell/festival.fish", "#{shell_dir}/festival.fish"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/camp.bash", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/camp"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/_camp", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_camp"]
    system_command "/bin/cp", args: ["#{staged_path}/completions/camp.fish", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/camp.fish"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/share/festival/shell/festival.bash", "#{HOMEBREW_PREFIX}/share/festival/shell/festival.zsh", "#{HOMEBREW_PREFIX}/share/festival/shell/festival.fish", "#{HOMEBREW_PREFIX}/etc/bash_completion.d/camp", "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_camp", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/camp.fish"]
  end

  # No zap stanza required

  caveats <<~EOS
    Homebrew installs static fest and camp completions. To activate navigation helpers
    (cgo, cr, csw, cint, fgo, fls) as well, add one line to your shell config:

      # bash (~/.bashrc)
      source \"$(brew --prefix)/share/festival/shell/festival.bash\"

      # zsh (~/.zshrc)
      source \"$(brew --prefix)/share/festival/shell/festival.zsh\"

      # fish (~/.config/fish/config.fish)
      source \"$(brew --prefix)/share/festival/shell/festival.fish\"
  EOS
end
