# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentStreamDbg < Formula
  desc "TUI debugger for multi-agent event streams (SSE, gRPC, ACP)"
  homepage "https://github.com/Obedience-Corp/agent-stream-dbg"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Obedience-Corp/agent-stream-dbg/releases/download/v0.1.1/agent-stream-dbg-0.1.1-macOS-x86_64.tar.gz"
      sha256 "4b731503ce420ed287f4580530c476e949179326e938a3755d0ac174802cc0ec"

      define_method(:install) do
        bin.install "agent-stream-dbg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Obedience-Corp/agent-stream-dbg/releases/download/v0.1.1/agent-stream-dbg-0.1.1-macOS-arm64.tar.gz"
      sha256 "3253daaaba1811f3607361a6eaeade5c7ffacff4cd423cbf04245b7f96bf2e97"

      define_method(:install) do
        bin.install "agent-stream-dbg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/agent-stream-dbg/releases/download/v0.1.1/agent-stream-dbg-0.1.1-linux-x86_64.tar.gz"
      sha256 "8c5040dbd2d6836e38aff1b3c8980b4dc6d9dd34f13830d33ae374459975a315"
      define_method(:install) do
        bin.install "agent-stream-dbg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/agent-stream-dbg/releases/download/v0.1.1/agent-stream-dbg-0.1.1-linux-arm64.tar.gz"
      sha256 "6fc430cfc5c352857d4174f04756ef1ae310502dbee575529373df63c174731e"
      define_method(:install) do
        bin.install "agent-stream-dbg"
      end
    end
  end

  test do
    assert_match "agent-stream-dbg", shell_output("#{bin}/agent-stream-dbg --help")
  end
end
