# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Festival < Formula
  desc "Festival Methodology CLI suite (fest + camp)"
  homepage "https://github.com/Obedience-Corp/festival"
  version "0.1.0"
  license "BUSL-1.1"

  on_macos do
    url "https://github.com/Obedience-Corp/festival/releases/download/v0.1.0/festival-0.1.0-macOS-all.tar.gz"
    sha256 "c3ca76f58980f6196f7a863795a04410d1cbf5da7821a8fb42ea12b81e5ca06a"

    define_method(:install) do
      bin.install "fest"
      bin.install "camp"
      bash_completion.install "completions/fest.bash" => "fest"
      zsh_completion.install "completions/_fest"
      fish_completion.install "completions/fest.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/festival/releases/download/v0.1.0/festival-0.1.0-linux-x86_64.tar.gz"
      sha256 "03868c1ad7fbfe554ef409cb945c7b73c4135486f425054d0b248e862ce2393d"
      define_method(:install) do
        bin.install "fest"
        bin.install "camp"
        bash_completion.install "completions/fest.bash" => "fest"
        zsh_completion.install "completions/_fest"
        fish_completion.install "completions/fest.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/festival/releases/download/v0.1.0/festival-0.1.0-linux-arm64.tar.gz"
      sha256 "d2bc802a473f151ef4904292fe74782d8f734c1c5e27b7523c513f8c988390dd"
      define_method(:install) do
        bin.install "fest"
        bin.install "camp"
        bash_completion.install "completions/fest.bash" => "fest"
        zsh_completion.install "completions/_fest"
        fish_completion.install "completions/fest.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To activate shell completions and camp shell integration, add to your shell config:

        # bash (~/.bashrc)
        eval "$(camp shell-init bash)"
        source <(fest completion bash)

        # zsh (~/.zshrc)
        eval "$(camp shell-init zsh)"
        source <(fest completion zsh)

        # fish (~/.config/fish/config.fish)
        camp shell-init fish | source
        fest completion fish | source
    EOS
  end

  test do
    system "#{bin}/fest", "--version"
    system "#{bin}/camp", "--version"
  end
end
