# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Festival < Formula
  desc "Festival Methodology CLI suite (fest + camp)"
  homepage "https://github.com/Obedience-Corp/festival"
  version "0.2.1"
  license "BUSL-1.1"

  on_macos do
    url "https://github.com/Obedience-Corp/festival/releases/download/v0.2.1/festival-0.2.1-macOS-all.tar.gz"
    sha256 "4090038c8d9214d67a3a837efaa50b3c6c5fca45ed959ebaa6822399a67d8a7f"

    define_method(:install) do
      bin.install "fest"
      bin.install "camp"
      bash_completion.install "completions/fest.bash" => "fest"
      zsh_completion.install "completions/_fest"
      fish_completion.install "completions/fest.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/festival/releases/download/v0.2.1/festival-0.2.1-linux-x86_64.tar.gz"
      sha256 "9f6c5aecff8bfdb791f43dcc69f83cb8766d7f415fe8aebc9d1aa7dbfff07f0c"
      define_method(:install) do
        bin.install "fest"
        bin.install "camp"
        bash_completion.install "completions/fest.bash" => "fest"
        zsh_completion.install "completions/_fest"
        fish_completion.install "completions/fest.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/festival/releases/download/v0.2.1/festival-0.2.1-linux-arm64.tar.gz"
      sha256 "324248a3a69e763c6f56bae273e514a3aaa5cd0836332f0bfae61ac237b90f73"
      define_method(:install) do
        bin.install "fest"
        bin.install "camp"
        bash_completion.install "completions/fest.bash" => "fest"
        zsh_completion.install "completions/_fest"
        fish_completion.install "completions/fest.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To activate shell completions and camp shell integration, add to your shell config:

        # bash (~/.bashrc)
        eval "$(camp shell-init bash)"
        source <(fest completion bash)

        # zsh (~/.zshrc)
        eval "$(camp shell-init zsh)"
        source <(fest completion zsh)

        # fish (~/.config/fish/config.fish)
        camp shell-init fish | source
        fest completion fish | source
    EOS
  end

  test do
    system "#{bin}/fest", "--version"
    system "#{bin}/camp", "--version"
  end
end
