# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Festival < Formula
  desc "Festival Methodology CLI suite (fest + camp)"
  homepage "https://github.com/Obedience-Corp/festival"
  version "0.2.0"
  license "BUSL-1.1"

  on_macos do
    url "https://github.com/Obedience-Corp/festival/releases/download/v0.2.0/festival-0.2.0-macOS-all.tar.gz"
    sha256 "f0fddc5927ab85b9e4423db9524e325e459972729251db689c406adfea40d9fd"

    define_method(:install) do
      bin.install "fest"
      bin.install "camp"
      bash_completion.install "completions/fest.bash" => "fest"
      zsh_completion.install "completions/_fest"
      fish_completion.install "completions/fest.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/festival/releases/download/v0.2.0/festival-0.2.0-linux-x86_64.tar.gz"
      sha256 "ea2878bf499f0ba58a240c3823bf01f160b26c3462bf1c47fe18c7906ebc39f0"
      define_method(:install) do
        bin.install "fest"
        bin.install "camp"
        bash_completion.install "completions/fest.bash" => "fest"
        zsh_completion.install "completions/_fest"
        fish_completion.install "completions/fest.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Obedience-Corp/festival/releases/download/v0.2.0/festival-0.2.0-linux-arm64.tar.gz"
      sha256 "403501d65b06f7f7733907d8f2a4d0918cc8e57e547292a0ff4fd50524cbb0ca"
      define_method(:install) do
        bin.install "fest"
        bin.install "camp"
        bash_completion.install "completions/fest.bash" => "fest"
        zsh_completion.install "completions/_fest"
        fish_completion.install "completions/fest.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To activate shell completions and camp shell integration, add to your shell config:

        # bash (~/.bashrc)
        eval "$(camp shell-init bash)"
        source <(fest completion bash)

        # zsh (~/.zshrc)
        eval "$(camp shell-init zsh)"
        source <(fest completion zsh)

        # fish (~/.config/fish/config.fish)
        camp shell-init fish | source
        fest completion fish | source
    EOS
  end

  test do
    system "#{bin}/fest", "--version"
    system "#{bin}/camp", "--version"
  end
end
